// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using renieldavid.webdev.Infrastructure.Domain;

#nullable disable

namespace renieldavid.webdev.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("renieldavid.webdev.Infrastructure.Domain.Models.StreamingAndService", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StreamingAndServices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1cef3b99-b69d-4b12-9b0a-b63c5fddcdc7"),
                            Abbreviation = "NFLX",
                            Description = "is an American subscription video on-demand over-the-top streaming service and production company based in Los Gatos, California. Founded in 1997 by Reed Hastings and Marc Randolph in Scotts Valley, California, it offers a film and television series library through distribution deals as well as its own productions, known as Netflix Originals.",
                            Title = "NETFLIX"
                        },
                        new
                        {
                            Id = new Guid("e9ff85ab-f0c1-4de9-a9f2-5bee39150e4f"),
                            Abbreviation = "APV",
                            Description = "Watch award-winning Prime Originals on the web or Prime Video app. Enjoy Anywhere. Watch The Grand Tour. Unlimited Streaming. Start Free Trial. Download and Go.",
                            Title = "amazon prime video"
                        },
                        new
                        {
                            Id = new Guid("e9735c93-7e74-4fbc-83e8-45d5999ccb1a"),
                            Abbreviation = "HIME",
                            Description = "Crunchyroll is an American subscription video on-demand over-the-top streaming service owned by Sony through a joint venture between Sony Pictures and Sony Music Entertainment Japan's Aniplex. The company primarily distributes films and television series from East Asian media, including Japanese anime outside Asia.",
                            Title = "Crunchyroll"
                        });
                });

            modelBuilder.Entity("renieldavid.webdev.Infrastructure.Domain.Models.Video", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DateOfPublish")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1cef3b99-b69d-4b12-9b0a-b63c5fddcdc7"),
                            DateOfPublish = new DateTime(2022, 11, 28, 13, 43, 7, 769, DateTimeKind.Local).AddTicks(2093),
                            Title = "Turning Red",
                            Type = 1,
                            VideoId = new Guid("00965ecf-acae-46fe-8775-d7834b07fd96")
                        },
                        new
                        {
                            Id = new Guid("e9ff85ab-f0c1-4de9-a9f2-5bee39150e4f"),
                            DateOfPublish = new DateTime(2022, 11, 28, 13, 43, 7, 769, DateTimeKind.Local).AddTicks(2117),
                            Title = "Master",
                            Type = 2,
                            VideoId = new Guid("7ce68d5c-5b65-495a-8a63-14aeb48da87d")
                        },
                        new
                        {
                            Id = new Guid("e9735c93-7e74-4fbc-83e8-45d5999ccb1a"),
                            DateOfPublish = new DateTime(2022, 11, 28, 13, 43, 7, 769, DateTimeKind.Local).AddTicks(2121),
                            Title = "Kimi",
                            Type = 2,
                            VideoId = new Guid("1d72f000-dbbd-419b-8af2-f571e1486ac2")
                        });
                });

            modelBuilder.Entity("renieldavid.webdev.Infrastructure.Domain.Models.Video", b =>
                {
                    b.HasOne("renieldavid.webdev.Infrastructure.Domain.Models.StreamingAndService", "StreamingAndService")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamingAndService");
                });
#pragma warning restore 612, 618
        }
    }
}
